apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: hello-flask
  ports:
  - port: 3232
    targetPort: 3232


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  selector:
    matchLabels:
      app: hello-flask
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - name: hello-flask
        image: ghcr.io/kshitijchoudha/flask-k8s-mf-template:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3232
